services:
  desarrollo:
    build:
      context: .
      args:
        - db=${db}
        - dbuser=${dbuser}
        - dbpass=${dbpass}
        - wild_user=${wild_user}
        - wild_password=${wild_password}
    ports: 
      - "5900:5900" # vnc server
      - "25:25" # email server
    volumes:
      - ./volumes/opt/wildfly/standalone:/opt/wildfly/standalone
      - ./volumes/etc/apache2:/etc/apache2
      - ./volumes/etc/sigma:/etc/sigma
      - ./volumes/home/sigma:/home/sigma
      - ./volumes/var/lib/mysql:/var/lib/mysql
