services:
  desarrollo:
    build:
      context: .
      args:
        - db=${db}
        - dbuser=${dbuser}
        - dbpass=${dbpass}
    ports: 
      - "5900:5900"
    command: "x11vnc -create -forever"
