services:
  desarrollo:
    build:
      context: .
      args:
        - db=${db}
        - dbuser=${dbuser}
        - dbpass=${dbpass}
        - wild_user=${wild_user}
        - wild_password=${wild_password}
        - vpn_user=${vpn_user}
        - vpn_password=${vpn_password}
        - USER=${USER}
        - PASSWORD=${PASSWORD}
    ports: 
      - "5901:5901" # vnc server
      - "25:25" # email server
    volumes:
      - ./volumes/opt/wildfly/standalone:/opt/wildfly/standalone
      - ./volumes/etc/apache2:/etc/apache2
      - ./volumes/home/sigma:/home/sigma
      - ./volumes/var/lib/mysql:/var/lib/mysql
      - ./volumes/etc/openfortivpn:/etc/openfortivpn
      - ./volumes/code:/code
    cap_add:
      - "NET_ADMIN"
      - "NET_RAW"

