services:
  desarrollo:
    build:
      context: .
      args:
        - db=${db}
        - dbuser=${dbuser}
        - dbpass=${dbpass}
        - wild_user=${wild_user}
        - wild_password=${wild_password}
    ports: 
      - "5900:5900" # vnc server
      - "25:25" # email server
    command: "x11vnc -create -forever"
