# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :
# Box / OS
VAGRANT_BOX = 'bento/debian-10'
VM_NAME = 'cloud'
VM_USER = 'sigma'

Vagrant.configure(2) do |config|
  config.vm.box = VAGRANT_BOX
  config.vm.hostname = VM_NAME
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 2048
  end

  if Vagrant.has_plugin?("vagrant-vbguest") then
        config.vbguest.auto_update = false
  end

  config.vm.network "forwarded_port", guest: 5901, host: 6901
  config.vm.network "forwarded_port", guest: 25, host: 25

  config.vm.provision "file", source: "./packages", destination: "/tmp/packages"
  config.vm.provision "shell", inline: "cp -r /tmp/packages / && rm -rf /tmp/packages"
  config.vm.provision "file", source: "./config", destination: "/tmp/config"
  config.vm.provision "shell", inline: "cp -r /tmp/config / && rm -rf /tmp/config"
  config.vm.provision "file", source: "./static", destination: "/tmp/static"
  config.vm.provision "shell", inline: "cp -r /tmp/static/* / && rm -rf /tmp/static"

  config.vm.provision "shell", path: "provision.sh"
  config.vm.provision "shell", path: "init.sh"
end

