services:
  desarrollo:
    image: enriqueesanchz/entorno:latest
    environment:
      - vpn_user=${vpn_user}
      - vpn_password=${vpn_password}
      - tigervncpasswd=${tigervncpasswd}
    ports:
      - "6901:5901" # vnc server
    volumes:
      - /home/ec2-user/volumes/opt/wildfly/standalone:/opt/wildfly/standalone
      - /home/ec2-user/volumes/etc/apache2:/etc/apache2
      - /home/ec2-user/volumes/home/sigma:/home/sigma
      - /home/ec2-user/volumes/var/lib/mysql:/var/lib/mysql
      - /home/ec2-user/volumes/etc/openfortivpn:/etc/openfortivpn
      - /home/ec2-user/volumes/code:/code
    devices:
      - /dev/ppp:/dev/ppp
    cap_add:
      - "NET_ADMIN"
      - "NET_RAW"

