name: ci

on:
  push:
    branches:
      - "main"

env:
  DB: sigma
  DBUSER: sigma
  DBPASS: sigmadb
  WILD_USER: admin
  WILD_PASSWORD: admin
  USER: enrique
  PASSWORD: 123456

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/entorno:latest
          build-args: |
              db=${{ env.DB }}
              dbuser=${{ env.DBUSER }}
              dbpass=${{ env.DBPASS }}
              wild_user=${{ env.WILD_USER }}
              wild_password=${{ env.WILD_PASSWORD }}
              USER=${{ env.USER }}
              PASSWORD=${{ env.PASSWORD }}
